version: '3'

services:

  emscripten-builder:
    user: ${UID}:${UID}
    image: seanmorris/php-emscripten-builder
    build:
      context: ./
      dockerfile: emscripten-builder.dockerfile
    environment:
      EMCC_CORES: 8
      ENVIRONMENT: ${ENVIRONMENT:-web}
    volumes:
      - ./:/src
    command: [bash]
