name: release
on:
  push:
    tags:
      - 'v*'
jobs:
  release:
    runs-on: "ubuntu-latest"
    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          branch: main
          github_token: ${{secrets.GITHUB_TOKEN}}
          name: PHP-7.4-web.wasm
          path: build/PHP-7.4-web.wasm
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          branch: main
          github_token: ${{secrets.GITHUB_TOKEN}}
          name: PHP-8.0.0-web.wasm
          path: build/PHP-8.0.0-web.wasm
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: build/*
